### ISSUE TITLE
Tick sound

### ISSUE THREAD

**Issue by CardinalSparrow** [CardinalSparrow/Clock-web-app#3]
The tick sound isn't working properly.

**Comment by Taejin101** [comment]
Are you talking about that pause it is taking at the end of audio completion.

**Comment by CardinalSparrow** [comment]
> Are you talking about that pause it is taking at the end of audio completion.

Exactly. The tick sound should coincide with each stoke of the second hand of the clock

**Comment by CardinalSparrow** [comment]
issue solved
